name: Vanilla Caves
version: 0.1.0

pipeline:
  - src.plugins.cave
  - src.plugins.cave_extra

meta:
  base_version: "1.19"
  overlay_versions:
    v1_20_5: "1.20.5"
    v1_21_7: "1.21.7"

data_pack:
  load: src/datapack
  description: {"text":"Vanilla Caves\n1.19 - 26.1", "color":"gray"}
  pack_format: 10
  min_format: 10
  max_format: 101
  supported_formats:
    min_inclusive: 10
    max_inclusive: 101
  overlays:
    - directory: v1_20_5
      min_format: 41
      max_format: 80
      formats:
        min_inclusive: 41
        max_inclusive: 80
    - directory: v1_21_7
      min_format: 81
      max_format: 101
      formats:
        min_inclusive: 81
        max_inclusive: 101

output: build
